# run.conf example

TEMP=400
timestep=0.001
tdamp=1.0

target_exx=0.202
target_eyy=0.0
target_ezz=0.0
target_gxy=0.0
target_gxz=0.0
target_gyz=0.0


stepscurrent=5000
stepsnext=0
current_exx=0.202
current_eyy=0.0
current_ezz=0.0
current_gxy=0.0
current_gxz=0.0
current_gyz=0.0


DUMPDIR=DUMP
MODEL=../../../../../../MACE.model-mliap_lammps.pt
