# run.conf example

TEMP=450
timestep=0.001
tdamp=1.0

target_exx=0.20
target_eyy=0.0
target_ezz=0.0
target_gxy=0.0
target_gxz=0.0
target_gyz=0.0


stepscurrent=0 # here I have independent non broken restarts. improved respect to previous usage, where I had rto run 1000 steps more, risking undetected breaking.
stepsnext=5000
current_exx=0.19
current_eyy=0.0
current_ezz=0.0
current_gxy=0.0
current_gxz=0.0
current_gyz=0.0


DUMPDIR=DUMP
MODEL=../../../../../../MACE.model-mliap_lammps.pt
