# run.conf example

TEMP=300
timestep=0.001
tdamp=1.0
nsteps=10000

max_exx=0.21
max_eyy=0.0
max_ezz=0.0
max_gxy=0.0
max_gxz=0.0
max_gyz=0.0

NSTRAINS=21
nsteps=10000

current_step=6999
current_strain=20
current_exx=0.20

DUMPDIR=DUMP
MODEL=../../../MACE.model-lammps.pt
