print("running", __file__)

from ase.io import read
from structural_analysis import broken
import sys
from pprint import pprint

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("USAGE: broken.py <filename>")
        sys.exit(2)
    
    print(__file__, "called with argv")
    pprint(sys.argv)
    try:
        # Read the lammps-data file generated by LAMMPS
        atoms = read(sys.argv[1], format='lammps-data')
        if broken(atoms):
            print("Status: BROKEN")
            sys.exit(1) # Exit with error code if broken
        else:
            print("Status: CLEAN")
            sys.exit(0) # Exit with success code if valid
    except Exception as e:
        print(f"Error reading file: {e}")
        sys.exit(2)