ATOM_NAME = C

FORCE_SETS = FORCE_SETS

# Band path
BAND = 0 0 0   1/2 0 0   1/3 1/3 0   0 0 0

BAND_LABELS = $\Gamma$ M K $\Gamma$
BAND_POINTS = 101
BAND_GRAPH = True

MESH = 51 51 51
DOS = .True.

LEGEND = .TRUE.
YLABEL = frequency [Hz]
TITLE = Band Dispersion

GROUP_VELOCITY = .TRUE.
